; Preencha com os IPs de `terraform output` (rode terraform apply antes)
[control_plane]
control-plane ansible_host=98.82.130.164 private_ip=172.31.78.182

[workers]
worker-1 ansible_host=3.238.236.174 private_ip=172.31.70.52
worker-2 ansible_host=44.222.187.99 private_ip=172.31.75.218

[k8s_nodes:children]
control_plane
workers

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/vockey.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
