# Generated by Django 6.0.2 on 2026-04-15 12:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tarefa_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarefa",
            options={
                "ordering": ["-prioridade", "-criada_em"],
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
            },
        ),
        migrations.AddField(
            model_name="tarefa",
            name="atualizada_em",
            field=models.DateTimeField(auto_now=True, help_text="Última atualização"),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="prioridade",
            field=models.IntegerField(
                choices=[(1, "Baixa"), (2, "Média"), (3, "Alta"), (4, "Urgente")],
                default=2,
                help_text="Nível de prioridade",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="vencimento",
            field=models.DateTimeField(
                blank=True, help_text="Data de vencimento", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="concluida",
            field=models.BooleanField(default=False, help_text="Status de conclusão"),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="criada_em",
            field=models.DateTimeField(auto_now_add=True, help_text="Data de criação"),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="descricao",
            field=models.TextField(
                blank=True, help_text="Descrição detalhada da tarefa"
            ),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="titulo",
            field=models.CharField(help_text="Título da tarefa", max_length=200),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
